In [78]:
import pandas as pd
import numpy as np
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, precision_score, recall_score\
    ,accuracy_score

churn_df = pd.read_csv('data/churn.csv')
d = {'yes': True, 'no': False}
churn_df.replace('no',False,inplace=True)
churn_df.replace('yes',True,inplace=True)
churn_df.replace('False.',False,inplace=True)
churn_df.replace('True.',True,inplace=True)
churn_df = churn_df.drop('State',1)
churn_df = churn_df.drop('Area Code',1)
churn_df = churn_df.drop('Phone',1)

In [100]:
y = churn_df.ix[:,-1].as_matrix()
X = churn_df.ix[:,0:-1]
X_train, X_test, y_train, y_test =\
    train_test_split(X, y, test_size=0.33, random_state=42)
RFC = RandomForestClassifier()
RFC.fit(X_train,y_train)
print RFC.score(X_test, y_test)
y_pred = RFC.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print cm
print precision_score(y_test, y_pred)
print recall_score(y_test, y_pred)

0.938181818182
[[933   7]
 [ 61  99]]
0.933962264151
0.61875


In [101]:
RFC1 = RandomForestClassifier(n_estimators=10,oob_score=True)
RFC1.fit(X_train,y_train)
print RFC1.score(X_test, y_test)
y_pred1 = RFC1.predict(X_test)
cm1 = confusion_matrix(y_test, y_pred1)
print cm1
print accuracy_score(y_test, y_pred1)
print precision_score(y_test, y_pred1)
print recall_score(y_test, y_pred1)

0.938181818182
[[934   6]
 [ 62  98]]
0.938181818182
0.942307692308
0.6125


In [102]:
Q = np.vstack((RFC.feature_importances_,X.columns))
print np.sort(Q,axis=1)[:,-5:]

[[0.06486159977488153 0.09122923785505849 0.11399269531049867
  0.11461558922956425 0.1602218660444108]
 ['Night Calls' 'Night Charge' 'Night Mins' 'VMail Message' 'VMail Plan']]


In [103]:
for i in [10,12,14,16,18,20]:
    RFC2 = RandomForestClassifier(n_estimators=i,oob_score=True)
    RFC2.fit(X_train,y_train)
    print '{} Trees'.format(i)
    print RFC2.score(X_test, y_test)
    y_pred2 = RFC2.predict(X_test)
    cm2 = confusion_matrix(y_test, y_pred2)
    print cm2
    print accuracy_score(y_test, y_pred2)
    print precision_score(y_test, y_pred2)
    print recall_score(y_test, y_pred2)
    print

10 Trees
0.942727272727
[[934   6]
 [ 57 103]]
0.942727272727
0.94495412844
0.64375

12 Trees
0.932727272727
[[931   9]
 [ 65  95]]
0.932727272727
0.913461538462
0.59375

14 Trees
0.942727272727
[[931   9]
 [ 54 106]]
0.942727272727
0.921739130435
0.6625

16 Trees
0.942727272727
[[931   9]
 [ 54 106]]
0.942727272727
0.921739130435
0.6625

18 Trees
0.948181818182
[[933   7]
 [ 50 110]]
0.948181818182
0.940170940171
0.6875

20 Trees
0.945454545455
[[932   8]
 [ 52 108]]
0.945454545455
0.931034482759
0.675

