In [92]:
import matplotlib.pyplot as plt
import numpy as np
import random
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from scipy.spatial.distance import euclidean

class Kmeans(object):
    def __init__(self):
        pass
    def predict(self, X, k, centroids):
        if centroids is None:
            centroids = random.sample(X,k)
        yhat = np.zeros(X.shape[0])
        for j,observation in enumerate(X):
            point_distance = {}
            for i,item in enumerate(centroids):
                point_distance[i] = euclidean(observation, item)
            yhat[j] = min(point_distance.items(), key=lambda x: x[1])[0]

        Z = np.hstack((X,yhat.reshape(-1,1)))
        new_centroids = []

        for m in xrange(k):
            new_centroids.append(Z[Z[:,-1] == m][:,0:-1].mean(axis=0))
        
        if np.allclose(new_centroids, centroids):
            sse = 0
            for n,centroid in enumerate(new_centroids):
                A = Z[Z[:,-1] == n][:,0:-1]
                for obs in A:
                    sse+= euclidean(obs, centroid)**2        
            return new_centroids, sse
        else:
            return self.predict(X,k,new_centroids)



iris = datasets.load_iris()
# print iris
# Q = iris.data[:, :4]
y = iris.target
# print Q
# print y    
for i in xrange(9):
    predictions, error = Kmeans().predict(Q,i+1,None)
    print np.array(predictions)
    print error
    print

[[ 5.84333333  3.054       3.75866667  1.19866667]]
680.8244

[[ 6.30103093  2.88659794  4.95876289  1.69587629]
 [ 5.00566038  3.36037736  1.56226415  0.28867925]]
152.368706477

[[ 6.85384615  3.07692308  5.71538462  2.05384615]
 [ 5.006       3.418       1.464       0.244     ]
 [ 5.88360656  2.74098361  4.38852459  1.43442623]]
78.945065826

[[ 5.25555556  3.67037037  1.5037037   0.28888889]
 [ 4.71304348  3.12173913  1.4173913   0.19130435]
 [ 6.85        3.07368421  5.74210526  2.07105263]
 [ 5.9016129   2.7483871   4.39354839  1.43387097]]
71.3362224245

[[ 5.88360656  2.74098361  4.38852459  1.43442623]
 [ 5.12173913  3.5173913   1.53043478  0.27826087]
 [ 4.69        3.085       1.385       0.19      ]
 [ 6.85384615  3.07692308  5.71538462  2.05384615]
 [ 5.52857143  4.04285714  1.47142857  0.28571429]]
69.2259515403

[[ 6.19655172  2.88275862  5.18275862  1.93448276]
 [ 5.          2.3         3.275       1.025     ]
 [ 7.12272727  3.11363636  6.03181818  2.13181818]
 [ 5.006